### ISSUE TITLE
Random Seed

### ISSUE THREAD

**Issue by Anuradha-Uggi** [Wickstrom/RELAX#2]
Hi,

Thanks for the nice work. There is no seed used to fix the random generation of masks, right? Due to this, the importance and uncertainty maps won't be consistent for the same image when run multiple times. Is there any reason why there is no seed used in the default setting of the code? 

Thanks

**Comment by Wickstrom** [comment]
Hi,

Thank you for the interest in our work and the encouraging comment.

Correct, there is no seed for the mask generation, so they will be different between multiple runs for the same image. I prefer the keep the code as minimal as possible, but if you wish to make RELAX deterministic it should be quite straight-forward to accomplish. For instance, including

`torch.use_deterministic_algorithms(True)`
`torch.manual_seed(0)`

before the forward pass of RELAX should remove the stochasticity between runs.

Hope that helps!
